kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hwameistor-ui
subjects:
- kind: ServiceAccount
  name: hwameistor-ui
  namespace: hwameistor
roleRef:
  kind: ClusterRole
  name: hwameistor-ui
  apiGroup: rbac.authorization.k8s.io
