
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: hwameistor-ui
  rules:
    - apiGroups: [ "*" ]
      resources:
        - "*"
      verbs: [ "*" ]
    - nonResourceURLs: [ "*" ]
      verbs: [ "*" ]
